GET http://127.0.0.1:5353/users

###

POST http://127.0.0.1:5353/users
Content-Type: application/json

{
  "email": "test@test.fr",
  "firstname": "john",
  "lastname": "doe",
  "password": "password",
}